Pydantic data models
mggg/plan-evaluation-processing pull request #24
Opened 2022-01-24 21:07 UTC by apizzimenti

Rather than a naïve JSON-to-object implementation, we use a pydantic data model.

2022-01-26 19:48 UTC, InnovativeInventor requested changes
I've got some minor suggestions (feel free to reject/accept) -- overall, this looks good to me!

2022-01-26 19:48 UTC, InnovativeInventor commented on evaltools/utils/JSON.py
> +class JSON(BaseModel):
Is `JSON` the best name for this class (since `json` is a built-in library that people can import)?

2022-01-26 19:48 UTC, InnovativeInventor commented on evaltools/utils/JSON.py
> +    title: Any = None
I think it's more idiomatic to use the `Optional` wrapper type. E.g.

```python
from typing import Optional

title: Optional[str]
```

2022-01-26 19:48 UTC, InnovativeInventor commented on evaltools/utils/JSON.py
> +            JSON(
You may want to rewrite this as:
```
JSON(**p)
```
which should be equivalent semantically.

2022-01-26 19:48 UTC, InnovativeInventor commented on evaltools/utils/JSON.py
> +def jsonify(location) -> list:
The types could be more specific here (which will help with IDE auto-completion):

```
from typing import List

def jsonify(location: str) -> List[JSON]
```

2022-02-02 19:38 UTC, apizzimenti commented
Testing out the Monday.com integration!

2022-02-04 17:14 UTC, merged